[605] Cadastrar Projeto
staketogether/st-v1-interface pull request #143
Opened 2023-11-01 18:11 UTC by paulobarcelosbr

<img width="549" alt="image" src="https://github.com/staketogether/st-v1-interface/assets/46430156/0bff62b4-086c-4bd0-869e-57e55db1eb7b">

<img width="561" alt="image" src="https://github.com/staketogether/st-v1-interface/assets/46430156/202dceb1-e50e-4feb-b86c-749d15b5d60c">

<img width="566" alt="image" src="https://github.com/staketogether/st-v1-interface/assets/46430156/675e8b71-706e-4a2c-b33e-fce913662531">

<img width="553" alt="image" src="https://github.com/staketogether/st-v1-interface/assets/46430156/a94b97a4-b77a-492c-9615-860494e73859">

<img width="563" alt="image" src="https://github.com/staketogether/st-v1-interface/assets/46430156/39a002b7-6590-4769-8faf-aefc4a4c49ba">

<img width="560" alt="image" src="https://github.com/staketogether/st-v1-interface/assets/46430156/5fc9f5d0-6c2a-4f6f-9659-b0d672d8dec3">

<img width="577" alt="image" src="https://github.com/staketogether/st-v1-interface/assets/46430156/ccb6a461-afbd-405a-bc55-a838b10588cb">

<img width="551" alt="image" src="https://github.com/staketogether/st-v1-interface/assets/46430156/37d952f7-1c9a-474b-951d-f4488f957a5d">

2023-11-03 15:02 UTC, 0xfabricio commented on package.json
> +    "contentful-management": "^11.2.0",
@paulobarcelosbr 

Explique o porque dessa lib

2023-11-03 15:04 UTC, 0xfabricio commented on package.json
> +    "formidable": "^3.5.1",
Explique o fluxo do porque dessa lib

2023-11-03 15:13 UTC, 0xfabricio commented on public/sw.js.map
O que é esse cara?

2023-11-03 15:14 UTC, 0xfabricio commented on src/components/gifts/GiftAccountConnected.tsx
> +    poolAddress: userGift?.address
Não entendi esse código

2023-11-03 15:15 UTC, 0xfabricio commented on src/components/project/Edit/ProjectEditForm.tsx
> +import Button from '@/components/shared/Button'
Deixa os códigos dos forms sempre separados (igual está aqui)

2023-11-03 15:16 UTC, 0xfabricio commented on src/components/project/Edit/ProjectEditForm.tsx
> +                    <span>Capa do projeto</span>
Texto Handwritter

2023-11-05 19:23 UTC, paulobarcelosbr commented on package.json
> +    "formidable": "^3.5.1",
essa lib foi adicionada por outro dev, como não estava sendo usada eu irei remover.

2023-11-05 19:24 UTC, paulobarcelosbr commented on package.json
> +    "contentful-management": "^11.2.0",
ela e responsavel pelo gerenciamento de Entrada de dados no contenful, esta sendo utilizada nos novos endpoint de criação e edição dos projetos.

2023-11-10 13:41 UTC, arthurmr96 requested changes

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/project/ProjectRegisterInfo.tsx
> +    }
Não entendi esse effect

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/project/ProjectRegisterInfo.tsx
> +    }
Por que está setando erro quando a conta é definida?

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/project/ProjectRegisteredCard.tsx
> +      case 'reproved':
rejected

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/shared/ConnectWallet.tsx
> +  }
Não era mais fácil colocar no arquivo de tradução não?

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/shared/GenericTransactionLoading.tsx
> +export default function GenericTransactionLoading({
TransactionSubmit

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/shared/GenericTransactionLoading.tsx
> +  onSuccessAction?: () => void
onSubmit

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/shared/inputs/Input.tsx
Por que criou um input genérico que tem o input e outro input separado?

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/shared/inputs/Select.tsx
Por que criou um input genérico que tem o select e outro select separado?

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/shared/inputs/TextArea.tsx
Por que criou um input genérico que tem o textare e outro texteare separado?

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/shared/layout/LayoutHeaderDesktop.tsx
> +  const { poolDetail: poolDetailUs } = useContentfulPoolDetails({
```suggestion
  const { poolDetail: hasProject } = useContentfulPoolDetails({
```

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/shared/layout/LayoutSidebarMobileMenu.tsx
> +  const { poolDetail: poolDetailUs } = useContentfulPoolDetails({
```suggestion
  const { poolDetail: hasProject } = useContentfulPoolDetails({
```

2023-11-10 13:41 UTC, arthurmr96 commented on src/components/stake/StakePoolInfo.tsx
> +  const { poolDetail, loading: poolDetailLoading } = useContentfulPoolDetails({ poolAddress: poolAddress })
```suggestion
  const { poolDetail, loading: poolDetailLoading } = useContentfulPoolDetails({ poolAddress })
```

2023-11-10 13:41 UTC, arthurmr96 commented on src/locales/en/common.json
> +        "reproved": "Reproved",
```suggestion
        "rejected": "Rejected",
```

2023-11-10 13:41 UTC, arthurmr96 commented on src/locales/pt/common.json
> +        "reproved": "Reprovado",
```suggestion
        "rejected": "Rejeitado",
```

2023-11-10 13:45 UTC, paulobarcelosbr commented on src/components/shared/layout/LayoutHeaderDesktop.tsx
> +  const { poolDetail: poolDetailUs } = useContentfulPoolDetails({
não pois eu utilizo esses dados em diversos locais por isso o nome principalmente referenciando que o idioma dele esta em ingles

2023-11-10 13:46 UTC, paulobarcelosbr commented on src/components/shared/ConnectWallet.tsx
> +  }
cara acredito que não, pois teria que acessar com o hook e são links que não mudam

2023-11-10 13:47 UTC, paulobarcelosbr commented on src/components/project/ProjectRegisterInfo.tsx
> +    }
por que o campo de carteira e setado automaticamente e caso o usuario troque a carteira a nova carteira precisa ser setada no lugar da antiga.

o setErro da logo, e por que trabalho o campo diferente dos demais. preciso realizar as trativas manualmente

2023-11-10 13:52 UTC, paulobarcelosbr commented on public/sw.js.map
esse arquivo é gerado quando rodamos um build, podemos removelo

2023-11-10 16:36 UTC, arthurmr96 approved these changes

2023-11-10 22:52 UTC, merged