[ 840 ] Incentivos
staketogether/st-v1-interface pull request #172
Opened 2024-01-17 17:27 UTC by paulobarcelosbr

2024-01-18 17:57 UTC, arthurmr96 requested changes

2024-01-18 17:57 UTC, arthurmr96 commented on package.json
> +    "@openzeppelin/merkle-tree": "^1.0.5",
Pode remover que não precisa mais

2024-01-18 17:57 UTC, arthurmr96 commented on .cspell.json
> +    "Merkle",
Ainda precisa?

2024-01-18 17:57 UTC, arthurmr96 commented on src/components/incentives/IncentivesCard.tsx
> +  }, [reportIncentive.reportBlock, provider])
Colocar o nome dos incentivos pra ser: Dezembro, Janeiro, Fevereiro... E assim por diante

2024-01-18 17:57 UTC, arthurmr96 commented on src/locales/en/common.json
> +      "ransomed": "Ransomed",
Redeemed

2024-01-19 17:51 UTC, 0xfabricio commented on src/config/chain.ts
> +  // {
remover?

2024-01-19 17:51 UTC, 0xfabricio commented on src/config/wagmi.ts
> +    // jsonRpcProvider({
remover?

2024-01-19 17:51 UTC, 0xfabricio commented on src/hooks/contracts/useAirdropClaim.tsx
> +  // const { registerWithdraw } = useMixpanelAnalytics()
precisa?

2024-01-19 18:07 UTC, 0xfabricio approved these changes

2024-01-19 18:14 UTC, 0xfabricio approved these changes

2024-01-19 18:15 UTC, merged