Feat/improved header layout
staketogether/st-v1-interface pull request #261
Opened 2024-05-08 18:47 UTC by samueldev43

![Captura de ecrã 2024-05-08 194624](https://github.com/staketogether/st-v1-interface/assets/71525496/d4973ee5-066e-490c-b884-33558a7dae4c)

header layout improved with addition of new elements and replace icons

2024-05-08 19:40 UTC, paulobarcelosbr commented on src/components/shared/layout/LayoutHeaderDesktop.tsx
> +  const currencyText = [
currenciesList: CurrencyType[] = [
]

2024-05-08 19:40 UTC, paulobarcelosbr commented on src/components/shared/layout/LayoutHeaderDesktop.tsx
> +            <span key={crn.key}>{currency === crn.currency ? `| ${crn.currency.toLocaleUpperCase()}` : ""}</span>
não e muito legal utilizar o map para essa situação tente algo assim currenciesList[currency]

2024-05-09 13:14 UTC, wellingtonfds approved these changes

2024-05-09 13:20 UTC, arthurmr96 requested changes

2024-05-09 13:20 UTC, arthurmr96 commented on src/components/shared/layout/LayoutHeaderDesktop.tsx
> +          <span>PT</span>
Tem que pegar de acordo com a língua do usuário

2024-05-09 13:20 UTC, arthurmr96 commented on src/locales/en/common.json
> +      "staking": "Investiments",
```suggestion
      "staking": "Investments",
```

2024-05-10 14:34 UTC, paulobarcelosbr commented on src/components/shared/layout/LayoutHeaderDesktop.tsx
> +  const isHome = router.pathname === basePath
voltar como era antes

2024-05-10 17:18 UTC, paulobarcelosbr approved these changes

2024-05-10 17:18 UTC, merged