feat: create new component and update assets detail
staketogether/st-v1-interface pull request #283
Opened 2024-05-27 15:46 UTC by samueldev43

![Captura de ecrã 2024-05-27 164533](https://github.com/staketogether/st-v1-interface/assets/71525496/5989ab2b-097d-47a0-bc3f-6ddba83621af)
![Captura de ecrã 2024-05-27 164520](https://github.com/staketogether/st-v1-interface/assets/71525496/000d0c79-5cbc-4986-8a09-5616ed7e3500)

created new component and updated assets details

2024-05-27 17:25 UTC, paulobarcelosbr commented on package.json
> +    "@types/node": "20.12.12",
por que instalou isso?

2024-05-27 17:25 UTC, paulobarcelosbr commented on src/components/assets/AssetsReceive.tsx
> +          <span>Compatível com as redes:</span>
falta tradução

2024-05-27 17:42 UTC, arthurmr96 submitted a review, later dismissed

2024-05-27 19:21 UTC, arthurmr96 requested changes

2024-05-27 19:21 UTC, arthurmr96 commented on src/components/assets/AssetsReceive.tsx
> +        </div>
Melhor pegar e listar a partir da config, que aí não tem que ficar adicionando na mão

2024-05-27 19:22 UTC, paulobarcelosbr commented on src/components/assets/AssetsActionsControl.tsx
> +    flex-wrap: wrap;
por que precisa dessa cara se o flex e column?

2024-05-28 13:06 UTC, paulobarcelosbr commented on src/components/assets/AssetsReceive.tsx
> +  console.log('')
remover console

2024-05-28 13:08 UTC, paulobarcelosbr commented on src/components/assets/AssetsReceive.tsx
> +          {chainConfigs.map(chain => (
vc vai tratar antes de chegar negar nessa parte, crie uma variavel e realize um filter

2024-05-28 13:08 UTC, paulobarcelosbr commented on src/components/assets/AssetsReceive.tsx
> +            <>
não precisa disso

2024-05-28 18:25 UTC, arthurmr96 requested changes

2024-05-28 18:25 UTC, arthurmr96 commented on src/components/assets/AssetsReceive.tsx
> +  const mainnetChain = chainConfigs.filter(chain => !chain.isTestnet)
```suggestion
  const mainnetChains = chainConfigs.filter(chain => !chain.isTestnet)
```

2024-05-28 18:25 UTC, arthurmr96 commented on src/components/assets/AssetsReceive.tsx
> +          {mainnetChain.map(chainFiltered => <NetworkIcons key={chainFiltered.chainId} network={chainFiltered.name.toLowerCase()} size={24}/>)}
```suggestion
          {mainnetChains.map(chainFiltered => <NetworkIcons key={chainFiltered.chainId} network={chainFiltered.name.toLowerCase()} size={24}/>)}
```

2024-05-29 12:25 UTC, arthurmr96 approved these changes

2024-05-29 13:19 UTC, merged