Feat/off ramp new config
staketogether/st-v1-interface pull request #288
Opened 2024-05-28 17:07 UTC by paulobarcelosbr

2024-05-28 18:45 UTC, arthurmr96 requested changes

2024-05-28 18:45 UTC, arthurmr96 commented on .github/workflows/rules_validation.yml
> +          echo NEXT_PUBLIC_PAYMASTER_CHZ_MAINNET=1 >> .env
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      value: { label: 'Telefone', value: 'PHONE' }
Colocar tradução

2024-05-28 18:45 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      value: { label: 'Aleatório', value: 'RANDOM' }
Colocar tradução

2024-05-28 18:45 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      value: { label: 'CPNJ', value: 'CPNJ' }
```suggestion
      value: { label: 'CNPJ', value: 'CNPJ' }
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      key: 'CPNJ',
```suggestion
      key: 'CNPJ',
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      <Select register={register('type')} options={options} title='Qual chave pix você deseja usar para receber?' />
Colocar tradução

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +  paymasterKey?: string
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: process.env.NEXT_PUBLIC_PAYMASTER_ETH_MAINNET,
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: process.env.NEXT_PUBLIC_PAYMASTER_OP_MAINNET,
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: process.env.NEXT_PUBLIC_PAYMASTER_ARB_MAINNET,
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: process.env.NEXT_PUBLIC_PAYMASTER_POL_MAINNET,
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: process.env.NEXT_PUBLIC_PAYMASTER_CHZ_MAINNET,
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: '0x',
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: 'XWk3Bd3kC.5a555601-f5ab-4fed-ab01-5ad406015e80',
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    name: 'OptimismSp',
Por que trocou o nome da rede para esse?

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: '0x',
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: '0x',
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/chain.ts
> +    paymasterKey: '0x',
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/config/env.ts
> +  }
```suggestion
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/hooks/contracts/useBalanceOf.tsx
> +      enabled: asset.type === 'native'
```suggestion
      enabled: asset.type === 'native' && walletAddress
```

2024-05-28 18:45 UTC, arthurmr96 commented on src/hooks/useEthersProvider.tsx
> +import { BrowserProvider, JsonRpcSigner } from 'ethers'
Qual a necessidade desse hook?

2024-05-28 18:45 UTC, arthurmr96 commented on src/hooks/usePaymasterSmartWallet.tsx
Remover

2024-05-29 12:03 UTC, arthurmr96 commented on src/components/asset/AssetBalanceCard.tsx
> +          {userTokenIsLoading ? <SkeletonLoading width={80} height={18} /> : <span>{truncateDecimal(userTokenBalance.balance, 6)}</span>}
```suggestion
          {userTokenIsLoading ? <SkeletonLoading width={80} height={18} /> : <span>{truncateDecimal(userTokenBalance.balance, asset.decimals)}</span>}
```

2024-05-29 12:06 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      CPF: () => (isValidCPF(key) && 'cpf invalido') || undefined,
Colocar tradução

2024-05-29 12:07 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      PHONE: () => (isValidPhone(key) && 'telefone invalido') || undefined,
Colocar tradução

2024-05-29 12:07 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      CNPJ: () => (isValidCNPJ(key) && 'cnpj invalido') || undefined,
Colocar tradução

2024-05-29 12:07 UTC, arthurmr96 commented on src/components/ramp/PixKeyStep.tsx
> +      EMAIL: () => (isValidEmail(key) && 'email invalido') || undefined
Colocar tradução

2024-05-29 12:08 UTC, arthurmr96 commented on src/components/ramp/ProcessingCheckoutOffRampStep.tsx
> +    return 'verified wallet network '
Colocar o texto: "Conectado à [rede]". Sendo traduzível

2024-05-29 15:29 UTC, arthurmr96 requested changes

2024-05-29 15:29 UTC, arthurmr96 commented on src/locales/pt/common.json
> +        "connectedNetwork": "Connected the [network]",
```suggestion
        "connectedNetwork": "Conectado em [network]",
```

2024-05-29 15:30 UTC, arthurmr96 approved these changes

2024-05-29 16:42 UTC, wellingtonfds approved these changes

2024-05-29 16:52 UTC, merged