Feat/add confirm modal transaction
staketogether/st-v1-interface pull request #35
Opened 2023-06-21 18:38 UTC by paulobarcelosbr

2023-06-22 12:16 UTC, arthurmr96 requested changes

2023-06-22 12:16 UTC, arthurmr96 commented on src/components/shared/GenericModal.tsx
> +export default function GenericModal({
Pode chamar só de Modal, já que vai ser o único genérico que vai ter. O que acha?

2023-06-22 12:16 UTC, arthurmr96 commented on src/components/stake/StakeForm.tsx
>    const handleActionButton = () => {
O nome não precisa ser muito genérico, eu colocaria algo como `openStakeConfirmation`

2023-06-22 12:16 UTC, arthurmr96 commented on src/components/stake/StakeForm.tsx
> +  const handleModalActionButton = () => {
No mesmo sentido, mudaria para `handleStakeConfirmation`

2023-06-22 12:16 UTC, arthurmr96 commented on src/hooks/useAddToWallet.tsx
> +        image: 'sethIcon',
Isso vai funcionar?

2023-06-22 17:15 UTC, 0xfabricio commented on src/components/shared/Modal.tsx
> +type GenericModal = {
ModalProps

2023-06-22 17:16 UTC, 0xfabricio commented on src/components/stake/StakeConfirmTransactionModal.tsx
> +type StakeConfirmModalProps = {
On code, use Deposit, instead Stake

DepositConfirmModal

2023-06-22 17:17 UTC, 0xfabricio commented on src/components/stake/StakeConfirmTransactionModal.tsx
> +import Image from 'next/image'
Archive name should be StakeConfirmModal

2023-06-22 17:18 UTC, 0xfabricio commented on src/components/stake/StakeConfirmTransactionModal.tsx
> +function StakeConfirmModal({
export default function StakeConfirmModal

2023-06-22 17:18 UTC, 0xfabricio commented on src/components/stake/StakeConfirmTransactionModal.tsx
> +export default StakeConfirmModal
put on top

2023-06-22 17:20 UTC, 0xfabricio commented on src/components/stake/StakeForm.tsx
> -  useEffect(() => {
Will we need from this guy?

2023-06-22 17:21 UTC, 0xfabricio commented on src/components/stake/StakeTransactionLoading.tsx
> +export default StakeTransactionLoading
put on top, expor default function

2023-06-22 17:22 UTC, 0xfabricio commented on src/config/chain.ts
> +      name: 'Etherscan',
put key ehere

etherscan

and on hook use


t('etherscan') 

add translation

2023-06-22 17:23 UTC, 0xfabricio commented on src/hooks/contracts/useDeposit.tsx
> +      try {
let's error happen

2023-06-22 17:23 UTC, 0xfabricio commented on src/hooks/contracts/useWithdraw.tsx
> +      try {
let's error happen

2023-06-22 17:24 UTC, 0xfabricio commented on src/hooks/useAddSethToWallet.tsx
> +        symbol: 'SETH',
use from translation (if we change that for some reason, this will break)

2023-06-22 17:25 UTC, 0xfabricio requested changes
Small Changes

2023-06-23 17:03 UTC, arthurmr96 approved these changes

2023-06-23 17:30 UTC, 0xfabricio approved these changes

2023-06-23 17:32 UTC, merged