Feat/add complements sidebar
staketogether/st-v1-interface pull request #44
Opened 2023-07-04 14:33 UTC by paulobarcelosbr

obs: vão ter atualizações de layout

![](https://cdn.discordapp.com/attachments/811234158314782730/1125793939224530954/image.png)
![](https://cdn.discordapp.com/attachments/811234158314782730/1125793939543310346/image.png)

2023-07-04 15:00 UTC, arthurmr96 requested changes

2023-07-04 15:00 UTC, arthurmr96 commented on src/components/shared/wallet/WalletByEthModal.tsx
> +export default function WalletByEthModal({ walletAddress, onBuyEthIsSuccess }: WalletByEthModalProps) {
```suggestion
export default function WalletBuyEthModal({ walletAddress, onBuyEthIsSuccess }: WalletBuyEthModalProps) {
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/components/shared/wallet/WalletByEthModal.tsx
> +type WalletByEthModalProps = {
```suggestion
type WalletBuyEthModalProps = {
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/components/shared/wallet/WalletByEthModal.tsx
> +export default function WalletByEthModal({ walletAddress, onBuyEthIsSuccess }: WalletByEthModalProps) {
Renomear também arquivo

2023-07-04 15:00 UTC, arthurmr96 commented on src/components/shared/wallet/WalletByEthModal.tsx
> +            placeholder={t('BuyEth.inputPlaceHolder')}
```suggestion
            placeholder={t('buyEth.inputPlaceHolder')}
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/components/shared/wallet/WalletByEthModal.tsx
> +          {t('BuyEth.modalButton')}
```suggestion
          {t('buyEth.modalButton')}
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/components/shared/wallet/WalletByEthModal.tsx
> +            <span className='error'>{t(`getFaucetErrorMessages.${errorMessage}`)}</span>
```suggestion
            <span className='error'>{t(`${errorMessage}`)}</span>
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/pages/api/faucet.ts
> +    return res.status(400).json({ message: 'addressHasAlready' })
```suggestion
    return res.status(400).json({ message: 'getFaucetErrorMessages.addressHasAlready' })
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/pages/api/faucet.ts
> +    return res.status(400).json({ message: 'faucetIsEmpty' })
```suggestion
    return res.status(400).json({ message: 'getFaucetErrorMessages.faucetIsEmpty' })
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/pages/api/faucet.ts
> +    return res.status(400).json({ message: 'invalidPasscode' })
```suggestion
    return res.status(400).json({ message: 'getFaucetErrorMessages.invalidPasscode' })
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/pages/api/faucet.ts
> +    return res.status(400).json({ message: 'invalidAddress' })
```suggestion
    return res.status(400).json({ message: 'getFaucetErrorMessages.invalidAddress' })
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/pages/api/faucet.ts
> +    return res.status(400).json({ message: 'passcodeIsRequired' })
```suggestion
    return res.status(400).json({ message: 'getFaucetErrorMessages.passcodeIsRequired' })
```

2023-07-04 15:00 UTC, arthurmr96 commented on src/pages/api/faucet.ts
> +    return res.status(400).json({ message: 'addressIsRequired' })
```suggestion
    return res.status(400).json({ message: 'getFaucetErrorMessages.addressIsRequired' })
```

2023-07-05 16:44 UTC, 0xfabricio commented on src/components/shared/Modal.tsx
> +    position: fixed;
esses positions estão certos?

não vão dar erro no mobile

2023-07-05 16:45 UTC, 0xfabricio commented on src/components/stake/StakeTransactionLoading.tsx
> +            <span>{t('viewOnExplorer')}</span>
não tem explorer mais, que tradução é essa?

2023-07-05 16:46 UTC, 0xfabricio approved these changes

2023-07-05 21:02 UTC, paulobarcelosbr commented on src/components/shared/Modal.tsx
> +    position: fixed;
esse position e para acertar o overlay do modal então fica certo no mobile

2023-07-05 21:54 UTC, merged