fixed the value you receive value subtracted 1 wei in the calculation
staketogether/st-v1-interface pull request #49
Opened 2023-07-06 15:35 UTC by paulobarcelosbr

2023-07-07 13:49 UTC, 0xfabricio requested changes
Implementação está errada, não precisa da função ali, os calculos sempre devem ser feitos com bigInt, esse calculo já tem na função do contrato, só usar.

2023-07-07 13:49 UTC, 0xfabricio commented on src/services/truncate.ts
> +  const etherAsBigInt = BigInt(Math.round(parseFloat(amountInEther) * Number(10 ** 18))) - BigInt(1)
Essa função não deveria estar aqui

Contas no frontend somente com bigint (math, parse float, crypto isso não existe)

Esse função tem que ser usada a Shares by eth no contrato.

2023-07-11 13:58 UTC, arthurmr96 requested changes

2023-07-11 13:58 UTC, arthurmr96 commented on src/components/stake/StakeForm.tsx
> +    ethers.parseUnits(amount || '0', 'ether').toString()
Isn't better treat the empty amount on the hook itself?

2023-07-11 13:58 UTC, arthurmr96 commented on src/hooks/contracts/usePooledShareByEth.tsx
> +export default function usePooledShareByEth(sharesAmount: bigint) {
```suggestion
export default function useSharesByPooledEth(ethAmount: bigint) {
```

2023-07-11 13:58 UTC, arthurmr96 commented on src/components/stake/StakeForm.tsx
> +            {`${t('youReceive')} ${type === 'deposit' ? truncateWei(shareByEth, 4) || '0' : amount}`}
Is it necessary this ` truncateWei(shareByEth, 4) || '0'`? Because `truncateWei` will always return a string and `shareByEth` will never be undefined

2023-07-11 13:58 UTC, arthurmr96 commented on src/hooks/contracts/usePooledShareByEth.tsx
> +export default function usePooledShareByEth(sharesAmount: bigint) {
Follow the name this method has on the contract. Also it's important to set the correct name for the argument to not confuse what is share and what is eth on this method

2023-07-11 15:09 UTC, paulobarcelosbr commented on src/components/stake/StakeForm.tsx
> +    ethers.parseUnits(amount || '0', 'ether').toString()
no, because I need to convert the amount value before sending and the parseUnits function doesn't receive empty.
I even thought about dealing with the hook, but this function is used in many places and it was breaking. I kept it original.

2023-07-11 17:16 UTC, arthurmr96 requested changes

2023-07-11 17:16 UTC, arthurmr96 commented on src/hooks/contracts/usePooledShareByEth.tsx
You need to rename the file too

2023-07-11 18:40 UTC, arthurmr96 approved these changes

2023-07-12 12:42 UTC, 0xfabricio commented on src/components/stake/StakeConfirmModal.tsx
> +                    <span className={`purple`}> {t('lsd.symbol')}</span> ={' '}
O que é isso?

={' '}

2023-07-12 12:42 UTC, 0xfabricio commented on src/components/stake/StakeConfirmModal.tsx
> +                    <span className={`purple`}> {t('lsd.symbol')}</span> ={' '}
What's this?

2023-07-12 12:42 UTC, 0xfabricio commented on src/components/stake/StakeConfirmModal.tsx
> +                    <span className={`purple`}> {t('lsd.symbol')}</span> ={' '}
={' '}

2023-07-12 12:43 UTC, 0xfabricio commented on src/components/stake/StakeForm.tsx
> +            {`${t('youReceive')} ${type === 'deposit' ? truncateWei(shareByEth, 4) || '0' : amount}`}
truncateWei(shareByEth, 4) || '0'

Do this generate false values?

2023-07-12 12:44 UTC, 0xfabricio approved these changes

2023-07-12 12:48 UTC, paulobarcelosbr commented on src/components/stake/StakeForm.tsx
> +            {`${t('youReceive')} ${type === 'deposit' ? truncateWei(shareByEth, 4) || '0' : amount}`}
the valuewhen amount value is 0 or undefined the contract does not return value

2023-07-12 12:58 UTC, merged